### ISSUE TITLE
不会编程可以运行吗？

### ISSUE THREAD

**Issue by cuixiaodong5211** [jsfaint/sentinel#1]
买了个vps，想用vps运行这个，可以批量登录吗？如何运行这个软件？能写个教程吗？我qq11067121.谢谢指导

**Comment by jsfaint** [comment]
1. 可以批量登录，填在config.json里面就可以了
2. 推送需要servchan的token，用github的帐号在这里登录就可以获取到 http://sc.ftqq.com/3.version
3. 在screen或者tmux里面把sentinel跑起来就可以了

## 配置
config内容如下
```json
{
    "token": "",
    "draw_day": 1,
    "accounts": [
        {"phone": "", "pass": ""}
    ]
}
```

token是从servchan获取到的填进去即可。
draw_day是提币的日期，1到5代表周一到周五，选一天填进去即可
accounts是帐号列表，按照以下的规则填写即可
```json
    "accounts": [
        {"phone": "130xxxxxxxx", "pass": "xxxxx"},
        {"phone": "131xxxxxxxx", "pass": "xxxxx"},
        {"phone": "135xxxxxxxx", "pass": "xxxxx"}
    ]
```

## 运行

1. 把sentinel二进制文件与config.json上传到vps，放到同一目录下
2. ssh登录到vps，然后在运行screen或者tmux中执行`./sentinel -log=info`即可


如果你不知道怎么编译，请告诉我你vps对应的os，我可以帮你编译

**Comment by cuixiaodong5211** [comment]
非常感谢你的及时回复，刚刚看了一下我的vps 是256的内存的，能跑的起来吗？系统是centos 6.5 32位
另外。我有一个xp的老电脑。能帮忙编译一个可以在xp上使用的版本吗？谢谢

**Comment by cuixiaodong5211** [comment]
可以发我QQ邮箱 谢谢啊

**Comment by jsfaint** [comment]
128MB的newifi都能跑起来~
二进制文件发你QQ邮箱里了
